version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    environment:
      PYTHONPATH: /home/circleci/project/
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
            pip install -r requirements.txt
            echo ${PYTHONPATH}
      - run:
          name: run test
          command: |
            . ../venv/bin/activate
            echo ${PYTHONPATH}
            pytest -v -l
          working_directory: tests/
      - store-test-results:
          path: test-reports
      - run:
          name: run test-cov
          command: |
            . ../venv/bin/activate
            pytest --cov=src
          working_directory: tests/
